### PR TITLE
Run an angular application inside the vscode webview

### PR DESCRIPTION
**Pull request by yashkurkure**
Added an angular application that renders inside the ProofStatePanel using WebViews.

Let me know if this works on your end. I have added some documentation on how to build and run this in `./docs`.

---
The gist of what changes I made and how this works:

The `./webview-ui` directory contains a full Angular application which can be run inside a browser by itself. The extension takes this application and runs it inside a WebView. The WebView is essentially like a mini browser of the extension inside which we run the Angular application.

Although you can run the code in `./webview-ui` as a standalone application in a browser, the rendering of the proof state depends on the extension. This is because:
1) The proofServer.py script runs the context of the extension.
2) The user input is taken from the extension side.

So the extension is entirely responsible for getting input from the user, processing it and then telling the angular application what it needs to display.

The message passing between the extension and the Angular application works both ways.
1) For the Angular application to communicate with the extension, `webview-ui/src/app/utilities/vscode.ts` exposes the VsCodeApi . Using `postMessage(<Json Object>)` you can pass a json object. The handler for this message lies in `src/panels/ProofStatePanel.ts` which sets message listeners in `_setWebviewMessageListener(webview: vscode.Webview)`

2) For the Extension to communicate with the Angular application use the `postMessage(<Json object>)` method of the webview instance.  See method `showGoals()` inside `ProofStatePanel.ts` for more details on how to get a reference to the webview instance. The handler for this message can be found in `webview-ui/src/app/app.component.ts` which defines the root component of the Angular app.  Look for the `ngOnInit()` method which deals with intialization code of the component. There you will find the event listener for handling messages from the extension.

### CODE REVIEW

**Comment by mansky1** [comment]
Is this approach of building the Angular app outside of the extension based on the example you found? It feels inefficient from a design perspective, but if that's the easiest way to make Angular work then I won't complain.

**Comment by mansky1** [comment]
Oh, relatedly, please include a link to any examples you copied code from somewhere in the comments.

**Comment by mansky1** [comment]
Confirmed that I can build and run it. (It's just supposed to look the same as before but with a "ProofState" heading, right?)

**Comment by yashkurkure** [comment]
Yes I found this example in Microsoft's official [repo](https://github.com/microsoft/vscode-webview-ui-toolkit-samples/tree/main/frameworks/hello-world-angular).

I found [another one](https://github.com/4gray/vscode-webview-angular) where the angular app is part of the extension. I am not entirely sure how this one works so I decided to stick with the official example.

Also yeah I haven't added the GUI part yet so it does not change what is displayed. I am researching Angular's components to try and figure out which GUI elements would be good to visualize this. Also I still need to look into the JSON object format that we get in the proofServer.py script before I decide on the Angular compnents.

**Comment by mansky1** [comment]
Okay! Please cite that repo in the code (maybe in docs/build-and-run.md) and then we can merge this.

**Comment by yashkurkure** [comment]
Created a new file for citations `./docs/citations.md`. I am sure we will have more as we go and it will be helpful for anyone who works on this in the future. 

Let me know if you want me format it differently or add more details about how the source was used! Otherwise we can merge.

**Comment by mansky1** [comment]
Looks good!

**Pull request merged**
